apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service2
  namespace: kickin
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
