apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service2
  namespace: kickin2
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort     
