apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-persistent-storage2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-persistent-storage2
        persistentVolumeClaim:
          claimName: task-pv-claim 

