apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment
  namespace: kickin76  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configmap-app
  template:
    metadata:
      labels:
        app: configmap-app
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: APP_MODE
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: APP_PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: DATABASE_URL
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: example-configmap

