apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kickin
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
